version: "3.1"

services:

  redis:
    container_name: rm_redis
    image: redis:5.0
    command: --appendonly no
    ports:
      - 6379:6379

  db:
    image: postgres:10-alpine
    container_name: rm_db
    ports:
      - 5432:5432
    tty: true
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

  adminer:
    image: adminer
    container_name: rm_adminer
    ports:
      - 8080:8080

  mailcatcher:
    image: schickling/mailcatcher
    container_name: rm_mailcatcher
    tty: true
    ports:
      - 1080:1080
      - 1025:1025

  api:
    image: cookiecode/base-ruby-on-rails
    container_name: rm_api
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
      - .bundle:/usr/local/bundle
      - .coverage:/var/www/.coverage
    stdin_open: true
    tty: true
    links:
      - db
      - redis

