---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  api/v1/beer_styles:
    get:
      summary: All Beer Styles
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Beer Style
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/beer_styles/check/style":
    get:
      summary: Check available name
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
  api/v1/beer_styles/{id}:
    get:
      summary: Show Beer Style
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Beer Style
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Beer Style
      tags:
      - Beer Styles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/beers":
    get:
      summary: All Beers
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Beer
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/beers/search":
    get:
      summary: Search beer by name
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/beers/{id}":
    get:
      summary: Show Beer
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Beer
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Beer
      tags:
      - Beers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/customers":
    get:
      summary: All Customers
      tags:
      - Customers
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Forgot password
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/api/v1/dishes/{dish_id}/ingredients":
    get:
      summary: All ingredients in dish
      tags:
      - Dish ingredients
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Add new ingredient to dish
      tags:
      - Dish ingredients
      responses:
        '401':
          description: Unauthorized
  "/api/v1/dishes/{dish_id}/ingredients/{food_id}":
    put:
      summary: Update ingredient in dish
      tags:
      - Dish ingredients
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Remove ingredient from dish
      tags:
      - Dish ingredients
      responses:
        '401':
          description: Unauthorized
  "/api/v1/dishes":
    get:
      summary: All Dishes
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Dish
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
  "/api/v1/dishes/search":
    get:
      summary: Search dish by name
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
  "/api/v1/dishes/{id}":
    get:
      summary: Show Dish
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Dish
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Dish
      tags:
      - Dishes
      responses:
        '401':
          description: Unauthorized
  "/api/v1/drinks":
    get:
      summary: All Drinks
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Drink
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
  "/api/v1/drinks/search":
    get:
      summary: Search Drink by name
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
  "/api/v1/drinks/{id}":
    get:
      summary: Show Drink
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Drink
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Drink
      tags:
      - Drinks
      responses:
        '401':
          description: Unauthorized
  "/api/v1/foods":
    get:
      summary: All Foods
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Food
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
  "/api/v1/foods/search":
    get:
      summary: Search Food by name
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
  "/api/v1/foods/{id}":
    get:
      summary: Show Food
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Food
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Food
      tags:
      - Foods
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wine_styles":
    get:
      summary: All Wine Styles
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine Style
      tags:
      - Update Wine Style
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Wine Style
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/makers":
    get:
      summary: All Makers
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Maker
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/makers/search":
    get:
      summary: Search Maker by name
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/makers/{id}":
    get:
      summary: Show Maker
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Maker
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Maker
      tags:
      - Makers
      responses:
        '401':
          description: Unauthorized
  "/api/v1/orders/{order_id}/items":
    get:
      summary: All Items from order
      tags:
      - Order Items
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Add new item to order
      tags:
      - Order Items
      responses:
        '401':
          description: Unauthorized
  "/api/v1/orders/{order_id}/items/{item_id}":
    put:
      summary: Update item in order
      tags:
      - Order Items
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Remove item in order
      tags:
      - Order Items
      responses:
        '401':
          description: Unauthorized
  "/api/v1/orders":
    get:
      summary: Show Wine Style
      tags:
      - Find Wine Style
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Wine Style
      tags:
      - Create Wine Style
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine Style
      tags:
      - Update Wine Style
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Wine Style
      tags:
      - Destroy Wine Style
      responses:
        '401':
          description: Unauthorized
  "/api/v1/organizations/{organization_id}/themes":
    get:
      summary: Show organization theme
      tags:
      - Organization Theme
      responses:
        '401':
          description: Unauthorized
  "/api/v1/organizations/{organization_id}/themes/{theme_id}":
    get:
      summary: Show organization theme
      tags:
      - Organization Theme
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update organization theme
      tags:
      - Organization Theme
      responses:
        '401':
          description: Unauthorized
  api/v1/organizations/{organization_id}/users:
    get:
      summary: All Organization users
      tags:
      - Organization Users
      responses:
        '401':
          description: Unauthorized
  "/api/v1/organizations":
    get:
      summary: Show Wine Style
      tags:
      - Find Wine Style
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Wine Style
      tags:
      - Create Wine Style
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine Style
      tags:
      - Update Wine Style
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Wine Style
      tags:
      - Destroy Wine Style
      responses:
        '401':
          description: Unauthorized
  "/api/v1/roles":
    get:
      summary: All Roles
      tags:
      - Roles
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Role
      tags:
      - Roles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/roles/{id}":
    get:
      summary: Show Role
      tags:
      - Roles
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Role
      tags:
      - Roles
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Role
      tags:
      - Roles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/tables":
    get:
      summary: All Tables
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Table
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
  "/api/v1/tables/search":
    get:
      summary: Search Table by name
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
  "/api/v1/tables/{id}":
    get:
      summary: Show Table
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Table
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Table
      tags:
      - Tables
      responses:
        '401':
          description: Unauthorized
  "/api/v1/users":
    get:
      summary: Show Wine Style
      tags:
      - Find Wine Style
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Wine Style
      tags:
      - Create Wine Style
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine Style
      tags:
      - Update Wine Style
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Wine Style
      tags:
      - Destroy Wine Style
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wine_styles/{id}":
    get:
      summary: Show Wine Style
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine Style
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Wine Style
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wine_styles/check/style":
    get:
      summary: Check available name
      tags:
      - Wine Styles
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wines":
    get:
      summary: All Wines
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
    post:
      summary: Create a Wine
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wines/search":
    get:
      summary: Search Wine by name
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
  "/api/v1/wines/{id}":
    get:
      summary: Show Wine
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
    put:
      summary: Update a Wine
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
    delete:
      summary: Destroy a Wine
      tags:
      - Wines
      responses:
        '401':
          description: Unauthorized
  "/auth/code":
    post:
      summary: Code received to reset your password
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/auth/confirmations":
    post:
      summary: Confirm your email
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/auth/sign_up":
    post:
      summary: Create new account
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/auth/reset_passwords":
    post:
      summary: Change your password, when forgot
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/auth/sign_in":
    post:
      summary: Sign In
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
  "/auth/sign_out":
    delete:
      summary: Sign out
      tags:
      - Auth
      responses:
        '401':
          description: Unauthorized
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
