database: &database
  db.username: postgres
  db.password: postgres
  db.host: localhost

mailer: &mailer
  mailer.address: smtp.gmail.com
  mailer.port: '587'
  mailer.user_name: fluffy.bunnybr@gmail.com
  mailer.password: cvxkxtoqrrwevdtt
  mailer.domain: gmail.com

aws: &aws
  provider: AWS
  access_key_id:
  secret_access_key:
  region:
  buket:

redis: &redis
  host: localhost
  port: '6379'

development:
  <<: *database
  <<: *mailer
  <<: *aws
  <<: *redis
  jwt_secret: ec19b7522ccd2d7e5e8af76a19f7b92b3db70265a55d1b4cc5c37d611123e0dc765ed12c9d931dbec7a4112e89b5f5be1840249947a6cec895c941d8cd93ce00

test:
  <<: *database
  <<: *mailer
  <<: *aws
  <<: *redis
  jwt_secret: ec19b7522ccd2d7e5e8af76a19f7b92b3db70265a55d1b4cc5c37d611123e0dc765ed12c9d931dbec7a4112e89b5f5be1840249947a6cec895c941d8cd93ce00

production:
  <<: *database
  <<: *aws
  <<: *redis
  mailer.host: restaurant_manager.com.br
  mailer.port: '80'
  jwt_secret: ec19b7522ccd2d7e5e8af76a19f7b92b3db70265a55d1b4cc5c37d611123e0dc765ed12c9d931dbec7a4112e89b5f5be1840249947a6cec895c941d8cd93ce00


